# -*- coding: utf-8 -*-
F = open("plik.txt","w")

print(F.closed, F.mode, F.name)
F.write("Początek pliku")
F.write("Kolejny napis")
F.writelines(["\n3 linia","\n4 linia","\n5 linia"])
F.close()
print(F.closed, F.mode, F.name)
G = open("plik.txt","r")
print (G.read(10))
print(G.tell())
G.seek(0)
print(G.tell())
G.seek(20)
print(G.tell())
G.seek(0,2)
print(G.tell())
G.seek(-5,1)
print(G.tell())